package com.aqms.sensorplot.model;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.aqms.sensorplot.FileUtil;

// POJO of the Sensor Plot

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName="Sensorplot")
public class SensorPlot {
	@DynamoDBHashKey(attributeName = "sensorId")
	@DynamoDBAutoGeneratedKey
	private String sensorId;

	@DynamoDBAttribute
	@Positive
	@Max(value=FileUtil.maxFloor)
	private int floor;
	
	@DynamoDBAttribute
	@Positive
	@Max(value=FileUtil.maxRoom)
	private int room;
}
