logging:
   file:
      name: LogInfo.log
   level:
      com:
         awsiot: INFO
server:
   port: 9001
spring:
   application:
      name: SENSOR-PLOT
aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKeyId: ${AWS_SECRET_ACCESS_KEY}
  dynamoDBEndpoint: dynamodb.ap-south-1.amazonaws.com
  region: ap-south-1